name: Deploy Docker Image Locally

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      run: |
        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

    - name: Pull Docker Image
      run: docker pull venkatesh01docker/github-actions-docker-java-app:0.0.1.Release

    - name: Run Docker Container
      run: docker run -p 5000:5000 venkatesh01docker/github-actions-docker-java-app:0.0.1.Release
