name: Azure Web App Container Deployment

on:
  push:
    branches:
      - master  # Change this to your default branch

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
       
      - name: Set up Docker
        uses: azure/docker-login@v1
        with:
          login-server: https://hub.docker.com/
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t senthilnata1/shell-java-app:0.0.1.Release .
          docker push senthilnata1/shell-java-app:0.0.1.Release

      - name: Deploy to Azure Web App
        uses: azure/webapps-container-deploy@v2
        with:
          app-name: azure-web-app-shell-java-app
          images: senthilnata1/shell-java-app:0.0.1.Release
